### ISSUE TITLE
Separate 2021 stuff from future stuff

### ISSUE THREAD

**Issue by fradotkso** [federicofusco/SpaceAppsChallenge#5]
I think it's better if we merge solarize-v1 and solarize-v2 directories into a 2021 directory, for a less messy work environment, or straight out delete solarize-v1

**Comment by federicofusco** [comment]
I agree, I'm refactoring some code in the solarize-v2 directory, and I'll include this change in the next commit. Although I'm going to have to reconfigure our vercel instances to deal with the new directory structure.

**Comment by federicofusco** [comment]
This issue was fixed in commit [8c8e082](https://github.com/federicofusco/spaceapps-challenge/commit/8c8e082cc41c611d3529fede000298fb400abe20).
