### ISSUE TITLE
Geolocation popup doesn't display on mobile when geolocation is off.

### ISSUE THREAD

**Issue by federicofusco** [federicofusco/SpaceAppsChallenge#8]
An automatic dialog should be displayed to prevent users from not understanding why the website isn't working.

This is should take advantage of an error system I'm currently setting up.

**Comment by fradotkso** [comment]
This happens also when geolocation is on.

**Comment by federicofusco** [comment]
> This happens also when geolocation is on.

This might be due to incorrect permissions. Although if you try it on an incognito page (to avoid position cache) on your mobile, the site should now show an error saying "Something went wrong! Is geolocation enabled?"

This issue was fixed (to my knowledge) in pull request #17. If this still doesn't work, contact me and describe the issue.
